### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by harr1193** [harr1193/MI-449-SS17-741-css-frameworks-p1twXJ#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://harr1193.github.io/MI-449-SS17-741-css-frameworks-p1twXJ/) and meets the following criteria:

- [x] Include the CSS and JS for Bootstrap 3 (not 4) in the page (including the "jQuery" dependency)
- [x] Use the `container` class to center your page content
- [x] Use a `navbar` class to display the name of your site and a list of at least 3 links (to past projects, or anything else) at the top of your page
- [x] Split your main content into 2 columns on large (`lg`) and medium (`md`) sized screens, but collapse them on top of each other on small (`sm`) and extra small (`xs`) screens
- [x] Use a `thumbnail` class on an at least one image in your page

**Comment by KatieMFritz** [comment]
Hi Kyle!

Really nice job with spacing, indentation, and using the Bootstrap grid system! 🎉 🌟 🔥 

Here are some things to fix:

### Must include JQuery 

Bootstrap's JavaScript has a **dependency** (code that must be included so other code will work) of JQuery. Try to find a CDN link to JQuery to include in your page.

Hint: Dependencies must be listed *before* the files/code that use them. 


### JavaScript goes at the end of the `body` element

You might not have gotten to this lesson yet, but you will soon! From [page 2 of the intro to JavaScript lesson](https://msu.lansing.codes/courses/MI-449-SS17-740/lessons/js-intro/2):

> Unlike `style` and `link`, which are used for CSS, the `script` element usually goes at the end of the `body` element, right before the closing `</body>` tag:

While there's [some debate over this](http://stackoverflow.com/questions/436411/where-is-the-best-place-to-put-script-tags-in-html-markup), it is the traditional place. We'll expect you to put your `script` elements at the end of the `body` for this and future projects, unless you make a compelling argument to do something different. 😄 

### Bootstrap Navbar

Check out how the navbar [on this page](https://getbootstrap.com/examples/navbar/) looks compared to your navbar. It's way fancier, right? That's because it's not just using `nav class="navbar"`; it's using a whole bunch of Bootstrap-specific markup (HTML). Start from that page, look at the Bootstrap docs (there's a link on that page), and see if you can make your navbar look more like the typical Bootstrap navbar. 👍 

* * *
Let me know when you're done, or if you get stuck along the way! 🚀

**Comment by harr1193** [comment]
Made the changes

**Comment by KatieMFritz** [comment]
Hey, great job updating the navbar! It looks fabulous now. Very professional. 💯 

I see that you've added jQuery and moved your JavaScript to the end, too. 👍 And the site STILL passes the W3 Validator. 🚀 

A few next steps to get this to perfect:

### Use correct file paths

Your site isn't able to load your Bootstrap JavaScript because the `src` in your script tag doesn't match with the structure of your project files:

`<script src="js/bootstrap.min.js"></script>`

You can see the error for yourself if you open up your site in Chrome, then type `Ctrl` + `Shift` + `J` (or `Cmd` + `Shift` + `J` on a Mac). See how it says "failed to load resource"? It even tells you what line of `index.html` the bad link is on. (If you see an error about `favicon.ico`, you can ignore it for now). 

**Try to correct the `src` for that `script` element so the server can find your Bootstrap javascript and you don't get that error anymore.** I'm happy to help if you get stumped!

* * *
### Add real links to Bootstrap navbar

From the project criteria: 
> Use a navbar class to display the name of your site and a list of at least 3 links (to past projects, or anything else) at the top of your page

Right now, all your links go to `#`, which just refreshes this page. Yes, technically, that's "anything else." 😝 But we want you to put real links in there so you get used to using Bootstrap's navbar *for real* - it's a very handy tool.

**Please replace the default Shop/About/Contact links, with their fake `#` URLs, with some real websites.** If you can't think of any, try MSU's homepage, your favorite (PG) YouTube video, and our course homepage.  

* * *
### Why we use unique, descriptive commit messages 

The beauty of git is that by making regular commits, you give yourself lots of "save points." If you mess up later, you can go back to when it was working.

This is a lot easier if each commit has a unique message explaining exactly what changed in that commit. However, for this project,  you used the same commit message (like "fixed navbar") more than once. If you needed to go back to a previous commit, you'd have to look at your code to figure out what changed, instead of being able to tell quickly from the commit log. Same if another developer, like me, needed to figure out what had changed.

For this project, I might use commit messages like this:

- "remove jquery from head and put nav links in bootstrap navbar html structure"
- "change nav to div in navbar"
- "more navbar changes"
- "add id to navbar-collapse - navbar seems to work now"

Do those make sense to you? Those aren't the _greatest_ commit messages, but sometimes when we're playing around with code, it is hard to be specific.

#### Some other tips for commits:

- **Only commit when the site is working.** That way, if you need to roll back, you'll go back to the last time your site was working, not some other broken version.
- **Commit one feature at a time.** If you need to undo something, this will make sure you don't break other features.
- **Describe what you did, and/or the status of the feature or site.** Did you _add_, _remove_, or _change_ something? Is a particular feature _working_ now? 

You don't have to worry about _redoing_ any of this - but **in the future, please give each commit its own specific message describing what you just changed.** It will help you be even more of a git wizard, and help you work better with other developers. :muscle:

**Comment by harr1193** [comment]
Added the real links and fixed the javascript src tag
